### ISSUE TITLE
UnicodeDecodeError when filename includes non ASCII characters

### ISSUE THREAD

**Issue by davuses** [ahupp/python-magic#287]
trying to read from a file whose filename is not ascii characters:
```py
magic.from_file("説明.txt")
```
And this gives me error:
```
Traceback (most recent call last):
  File "G:\BaiduNet\unarchive.py", line 64, in <module>
    magic.from_file("説明.txt")
  File "C:\Users\davuses\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\magic.py", line 135, in from_file
    return m.from_file(filename)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\davuses\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\magic.py", line 89, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\davuses\AppData\Local\Programs\Python\Python311\Lib\site-packages\magic\magic.py", line 214, in maybe_decode
    return s.decode('utf-8')
           ^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe6 in position 16: invalid continuation byte
```
If I rename the file to ASCII name, say `file.txt`, the problem disappears.

Also, if I use `.from_buffer()`, there's no issue:
```py
magic.from_buffer(open("説明.txt", "rb").read(2048), mime=True)
```
weird, not sure if this is related to this issue #205 

The package is installed with `pip install python-magic-bin` on WIndows 11, Python3.11

**Comment by silente** [comment]
Hi, I have the same problem. 

My code is:

`magic.from_file(file_path, mime=True`

My error is:

```
  File "C:\Program Files\Python38\lib\site-packages\magic\magic.py", line 135, in from_file
    return m.from_file(filename)
  File "C:\Program Files\Python38\lib\site-packages\magic\magic.py", line 89, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
  File "C:\Program Files\Python38\lib\site-packages\magic\magic.py", line 214, in maybe_decode
    return s.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 57: invalid continuation byte
```

I tried to edit "C:\Program Files\Python38\lib\site-packages\magic\magic.py", line 214 from  `return s.decode('utf-8')` to ` return s.decode('utf-8', errors='ignore')` or `return s.decode('utf-8', errors='replace')` but I still encounter the problem.

**Comment by ember91** [comment]
This happens if the system encoding is not UTF-8 and unicode characters are provided in the file path. Most often this is a problem on Windows.

For details, see `file_or_fd()` in `src/magic.c` in the libmagic source code. It uses `open()` which assumes the system encoding unless a locale has been set with e.g. `setlocale()`. In this repository it assumes that the file path is UTF_8 in `coerce_filename()` in `__init__.py`.

Some solutions are:
  - Ensure the dynamic library loaded with python-magic sets its locale to UTF-8 in some way before `open()`.
  - Temporarily move or symlink the file to a more accessible path before `from_file()`.
  - Read a number of bytes from the file in Python and pass them to `from_buffer()` instead
  - Open a file in Python and pass its descriptor to `from_descriptor()`. I haven't made it work unfortunately.

Another idea I had was to encode the file path as a byte string in the system encoding, but due to another bug that doesn't work.

**Comment by ahupp** [comment]
You are using python-magic-bin, which is an ancient fork of this library; this particular bug was fixed in python-magic quite a while ago.

**Comment by ember91** [comment]
It's not fixed. See my comment.

Right now it's not taken into account what encoding the underlying library uses. My libmagic dll at least seems to assume ACP, while this library seems to assume UTF-8.
